name: Procesar PDF y actualizar JSON

on:
  push:
    paths:
      - 'pdf/horario.pdf'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r parser/requirements.txt

      - name: Procesar PDF
        run: python parser/parse_pdf.py

      - name: Commit JSON
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/salas.json
          git commit -m "Actualizaci√≥n desde PDF" || echo "Sin cambios"
          git push
